# Generated by Django 5.0.6 on 2026-09-29 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmns', '0003_initial'),
        ('pipelines', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_uid', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='다이어그램 식별자')),
                ('xml', models.TextField(verbose_name='실행한 BPMN XML')),
                ('start', models.CharField(blank=True, max_length=128, verbose_name='시작 이벤트')),
                ('status', models.CharField(choices=[('pending', '대기'), ('running', '실행 중'), ('succeeded', '성공'), ('failed', '실패')], db_index=True, default='pending', max_length=16, verbose_name='상태')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='입력값')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='최종 값')),
                ('error', models.TextField(blank=True, verbose_name='오류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청일')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='종료')),
                ('diagram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='bpmns.bpmndiagram', verbose_name='다이어그램')),
            ],
            options={
                'verbose_name': '로직 실행',
                'verbose_name_plural': '로직 실행',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='순서')),
                ('node_id', models.CharField(max_length=128, verbose_name='노드 id')),
                ('node_type', models.CharField(max_length=64, verbose_name='노드 종류')),
                ('node_name', models.CharField(blank=True, max_length=255, verbose_name='노드 이름')),
                ('scope_id', models.CharField(blank=True, max_length=128, verbose_name='범위')),
                ('status', models.CharField(max_length=16, verbose_name='상태')),
                ('inputs', models.JSONField(blank=True, default=dict, verbose_name='입력')),
                ('outputs', models.JSONField(blank=True, default=dict, verbose_name='출력')),
                ('request', models.JSONField(blank=True, default=dict, verbose_name='요청')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='응답')),
                ('flows', models.JSONField(blank=True, default=list, verbose_name='나간 흐름')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='경고')),
                ('error', models.TextField(blank=True, verbose_name='오류')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='시도 횟수')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='시작')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='소요(ms)')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipelines.pipelinerun', verbose_name='실행')),
            ],
            options={
                'verbose_name': '실행 단계',
                'verbose_name_plural': '실행 단계',
                'ordering': ['run', 'seq'],
            },
        ),
    ]
