apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpmn-processor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpmn-processor
  template:
    metadata:
      labels:
        app: bpmn-processor
    spec:
      containers:
        - name: bpmn-processor
          image: localhost:32000/bpmn-processor:latest

---
apiVersion: v1
kind: Service
metadata:
  name: bpmn-processor-service
spec:
  selector:
    app: bpmn-processor
  ports:
    - name: bpmn-processor
      protocol: TCP
      port: 9901
      targetPort: 9901

---
apiVersion: v1
kind: Service
metadata:
  name: bpmn-processor-nodeport
  labels:
    app.kubernetes.io/name: bpmn-processor-nodeport
    app.kubernetes.io/part-of: bpmn-processor-nodeport
spec:
  type: NodePort
  ports:
  - name: bpmn-processor
    port: 9901
    targetPort: 9901
    nodePort: 9901
    protocol: TCP
  selector:
    app: bpmn-processor
