apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpmn-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpmn-backend
  template:
    metadata:
      labels:
        app: bpmn-backend
    spec:
      containers:
        - name: bpmn-backend
          image: bpmn-backend:latest
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: bpmn-backend-service
spec:
  selector:
    app: bpmn-backend
  ports:
    - name: bpmn-backend
      protocol: TCP
      port: 1337
      targetPort: 1337
