# Generated by Django 5.0.6 on 2026-06-08 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitaltwins', '0002_digitaltwincalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='이름')),
                ('description', models.TextField(blank=True, default='', verbose_name='설명')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='설정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '디지털 트윈',
                'verbose_name_plural': '디지털 트윈',
            },
        ),
        migrations.CreateModel(
            name='DigitalTwinSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='이름')),
                ('category', models.CharField(blank=True, default='demo', max_length=64, verbose_name='카테고리')),
                ('url', models.CharField(help_text='상대(/api/...) 또는 절대 URL', max_length=255, verbose_name='엔드포인트 URL')),
                ('enabled', models.BooleanField(default=True, verbose_name='활성화')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='메타')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '디지털 트윈 소스',
                'verbose_name_plural': '디지털 트윈 소스',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DigitalTwinCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='POST', max_length=8, verbose_name='메서드')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='경로')),
                ('request_body', models.JSONField(blank=True, default=dict, verbose_name='요청 바디')),
                ('response_body', models.JSONField(blank=True, default=dict, verbose_name='응답 바디')),
                ('status_code', models.IntegerField(default=200, verbose_name='상태코드')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='소요시간(ms)')),
                ('error', models.TextField(blank=True, default='', verbose_name='오류')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='digitaltwins.digitaltwinsource')),
            ],
            options={
                'verbose_name': '디지털 트윈 호출 로그',
                'verbose_name_plural': '디지털 트윈 호출 로그',
                'ordering': ('-created_at',),
            },
        ),
    ]
