# Generated by Django 5.0.6 on 2026-06-08 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm', '0005_normalize_ollama_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='이름')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('custom', 'Custom')], default='ollama', max_length=32, verbose_name='제공자')),
                ('base_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Base URL')),
                ('api_key', models.CharField(blank=True, default='', help_text='환경변수 사용 권장', max_length=255, verbose_name='API Key(옵션)')),
                ('model_name', models.CharField(blank=True, default='', max_length=128, verbose_name='모델명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본값')),
                ('enabled', models.BooleanField(default=True, verbose_name='활성화')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='메타')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'LLM 설정',
                'verbose_name_plural': 'LLM 설정',
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='이름')),
                ('template', models.TextField(help_text='프롬프트 템플릿 본문', verbose_name='템플릿')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='메타')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '프롬프트 템플릿',
                'verbose_name_plural': '프롬프트 템플릿',
            },
        ),
        migrations.CreateModel(
            name='LlmCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='프롬프트')),
                ('response', models.TextField(blank=True, default='', verbose_name='응답')),
                ('tokens_in', models.IntegerField(default=0, verbose_name='입력 토큰')),
                ('tokens_out', models.IntegerField(default=0, verbose_name='출력 토큰')),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='비용(USD)')),
                ('status', models.CharField(choices=[('success', '성공'), ('error', '오류')], default='success', max_length=16, verbose_name='상태')),
                ('error', models.TextField(blank=True, default='', verbose_name='오류')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='소요시간(ms)')),
                ('request_meta', models.JSONField(blank=True, default=dict, verbose_name='요청 메타')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='llm.llmconfig')),
            ],
            options={
                'verbose_name': 'LLM 호출 로그',
                'verbose_name_plural': 'LLM 호출 로그',
                'ordering': ('-created_at',),
            },
        ),
    ]
