# Generated by Django 5.0.6 on 2026-06-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpmns', '0002_alter_bpmndiagram_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpmnDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, db_index=True, max_length=64, unique=True, verbose_name='식별자')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='제목')),
                ('xml', models.TextField(verbose_name='BPMN XML')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'BPMN 다이어그램',
                'verbose_name_plural': 'BPMN 다이어그램',
            },
        ),
    ]
